In [2]:


import tensorflow as tf
import random
from tensorflow import keras
from tensorflow.python.keras.layers.recurrent_v2 import LSTM

import data_generator


In [5]:
# generate the data

x_set = [];
y_set = [];

for i in range(0,10):
    graphset = data_generator.get_graphset(i);
    x_set.append(graphset[0]);
    y_set.append(graphset[1]);

In [6]:
# split the data into training and testing sets

half = int(len(x_set)/2);

print(f'half: {half}')
x_train = x_set[0:half]
x_test = x_set[half:]

y_train = x_set[0:half]
y_test = x_set[half:]


half: 5


In [7]:
# print some data diagnostics to ensure we correctly obtained data sets

print("number of x data points:");
print(len(x_train[1]));


print("number of y data points:");
print(len(y_train[1]));

assert(len(x_train) == len(y_train));
print(f"\nNumber of training graph-solution sets: {len(x_train)}")

assert(len(x_test) == len(y_test));
print(f"Number of testing graph-solution sets: {len(x_test)}")

number of x data points:
5000
number of y data points:
5000

Number of training graph-solution sets: 5
Number of testing graph-solution sets: 5


In [10]:
#build the model by stacking layers; choose optimizer and loss function. Here we set the activation function to a 'relu'
model = tf.keras.models.Sequential([
  tf.keras.layers.LSTM(28),
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

print("model built");

model built


In [12]:
# get the predictions for the second datapoint
predictions = model(x_train[0])

# print the raw predictions fort that datapoint. Note that these are "logits" or "log-odds" scores, which is related to the probability, 
# and also is the inverse of the sigmoid function
print("logits prediction: ");
print(predictions);

# we can use the softmax function to convert these logits to probabilities for each preciction class
print("odds prediction: ");
print(tf.nn.softmax(predictions).numpy());



ValueError: Layer sequential_1 expects 1 input(s), but it received 5 input tensors. Inputs received: [<tf.Tensor: shape=(5000,), dtype=float64, numpy=
array([ 284191.94963941,  284663.94190978,  285134.17099082, ...,
       2728518.14283222, 2728639.50959567, 2728760.8612571 ])>, <tf.Tensor: shape=(5000,), dtype=float64, numpy=
array([0.96409574, 0.96406287, 0.96403002, ..., 0.80598931, 0.80596096,
       0.80593261])>, <tf.Tensor: shape=(5000,), dtype=float64, numpy=
array([1.00010647, 1.00010666, 1.00010684, ..., 1.00314408, 1.0031451 ,
       1.00314612])>, <tf.Tensor: shape=(5000,), dtype=float64, numpy=
array([0.99999969, 0.99999969, 0.99999969, ..., 0.99995431, 0.99995429,
       0.99995427])>, <tf.Tensor: shape=(5000,), dtype=float64, numpy=
array([1.        , 1.        , 1.        , ..., 1.00000066, 1.00000067,
       1.00000067])>]